export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_REDIRECT_PATH = 'AUTH_REDIRECT_PATH';

export const LOAD_PROJECTS_START = 'LOAD_PROJECTS_START';
export const ADD_PROJECT_FAIL = 'ADD_PROJECT_FAIL';
export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';
export const FETCH_PROJECTS_FAIL = 'FETCH_PROJECTS_FAIL';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAIL = 'DELETE_PROJECT_FAIL';
export const EDIT_PROJECT_SUCCESS = 'EDIT_PROJECT_SUCCESS';

export const FETCH_TASKS_START = 'FETCH_TASKS_START';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAIL = 'FETCH_TASKS_FAIL';
export const ADD_TASK_ITEM_SUCCESS = 'ADD_TASK_ITEM_SUCCESS';
export const ADD_TASK_ITEM_FAIL = 'ADD_TASK_ITEM_FAIL';
export const REMOVE_TASK_ITEM_SUCCESS = 'REMOVE_TASK_ITEM_SUCCESS';
export const REMOVE_TASK_ITEM_FAIL = 'REMOVE_TASK_ITEM_FAIL';
export const EDIT_TASK_ITEM_SUCCESS = 'EDIT_TASK_ITEM_SUCCESS';
export const EDIT_TASK_ITEM_FAIL = 'EDIT_TASK_ITEM_FAIL';
export const SORT_TASK_ITEM_SUCCESS = 'SORT_TASK_ITEM_SUCCESS';
export const SORT_TASK_ITEM_FAIL = 'SORT_TASK_ITEM_FAIL';

export const CLEAR_COMMENTS = 'CLEAR_COMMENTS';
export const FETCH_COMMENTS_START = 'FETCH_COMMENTS_START';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAIL = 'FETCH_COMMENTS_FAIL';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAIL = 'ADD_COMMENT_FAIL';